### ISSUE TITLE
Undefined functions

### ISSUE THREAD

**Issue by ys-li16** [VU-BEAM-Lab/ADMIRE#2] opened 2022-04-06 03:29 UTC
My operation system is Windows 10, and Matlab version is R2016a. MinGW is installed as the C compiler.

When I tried to compile the CPU implementation C code with "mex -v C:\xxx\ADMIRE\ADMIRE_Code\CPU_Implementation_Code\ccd_double_precision.c", errors were reported: "undefined reference to `mxGetData' (`mxMalloc' and `mxFree')". I checked code and found it seemed those functions (`mxGetData' `mxMalloc' and `mxFree') were not defined in 'ccd_double_precision.c' nor 'mex.h'.

Could you please give me some help? Many thanks!

**Comment by Christopher-Khan** [comment] 2022-04-06 04:30
Hi @ys-li16 . I think it might be caused by using MinGW. I've previously tested this code on my Windows 10 machine using Microsoft Visual Studio 2017 as the C/C++ compiler. Can you try installing this compiler and then compiling. If you look at the documentation under CPU Implementation Setup, I give a link to where you can download the compiler. If you still can't get it to work, let me know, and I can try sending you an already compiled MEX-file.

I hope this helps!
Christopher Khan

**Comment by ys-li16** [comment] 2022-04-06 08:50
Hi Christopher, 
Thanks for your kind reply.
I have made it. It was not caused by using MinGW, but one with wrong version. Only TDM-gcc MinGW 4.9.2 was supported (More information could be found at https://ww2.mathworks.cn/matlabcentral/answers/345391-how-to-install-mingw-4-9-2-for-matlab). I downloaded it from https://github.com/mathworks/MinGW_492/releases and correctly set the path. It finally works.
Yongshuai Li

**Comment by Christopher-Khan** [comment] 2022-04-06 09:07
Hi Yongshuai. I'm glad you were able to get it to work. Just as a note, if you end up using the GPU version of ADMIRE instead of the CPU version, you'll probably have to use the compiler that comes with Microsoft Visual Studio instead of MinGW in order to compile the MEX-functions that contain CUDA code.

I'm going to go ahead and close this issue, but let me know if you have any more questions!
Christopher Khan

**Comment by Christopher-Khan** [comment] 2022-04-06 09:08
Hi Yongshuai. I'm glad you were able to get it to work. Just as a note, if you end up using the GPU version of ADMIRE instead of the CPU version, you'll probably have to use the compiler that comes with Microsoft Visual Studio instead of MinGW in order to compile the MEX-functions that contain CUDA code.

I'm going to go ahead and close this issue, but let me know if you have any more questions!
Christopher Khan

**Closed as completed by Christopher-Khan** 2022-04-06 09:08 UTC
